### ISSUE TITLE
NPC isn't spawning.

### ISSUE THREAD

**Issue by FuriousLeech** [Manliketjb/Blackmarket#3]
/market works however there is not an NPC spawning at any of the coordinates at the times its open.

**Comment by Manliketjb** [comment]
fixed now

**Comment by FuriousLeech** [comment]
npc works, however now the market wont open when using the npc. is it because the /market command is enabled?

**Comment by OGPandaYT** [comment]
You need to change the trigger in the Client for QB-Target to Blackmarket:client:openstore but I am getting an issue where my mouse is stuck when closing.

**Comment by OGPandaYT** [comment]
Nevermind solved it.

**Comment by Manliketjb** [comment]
> You need to change the trigger in the Client for QB-Target to Blackmarket:client:openstore but I am getting an issue where my mouse is stuck when closing.

done that, what you do to fix the mouse issue, personally i've never had that issue but a few others have
